trigger:
  - master
pr:
  - master

variables:
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestId)
  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(Build.SourceBranchName)

jobs:
  - job: main
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: npm ci
      - script: npx nx format:check --base=origin/master
      - script: npx nx affected --base=origin/master -t lint
      - script: npx nx affected --base=origin/master -t test
      - script: npx nx affected --base=origin/master -t build